name: Update of my Readme.md

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          BLOCKS: ->
          SHOW_MASKED_TIME: true
          SHOW_TIME: true
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
