name: Update README.md

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update my development statistics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
          SHOW_TIME: true
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
